cache: './cache/html/AnImmortalsRetirement'
callbacks: 'books.AnImmortalsRetirement.cbs.Callbacks'
book:
    title: "An Immortal's Retirement: To Achieve Peace" 
    author: Malaklein 
    epub_filename: out/AnImmortalsRetirement.epub
    cover_image: https://www.royalroadcdn.com/public/covers-large/65789-an-immortals-retirement-to-achieve-peace.jpg
    css_filename: 'kindle.css'
    entry_point: https://www.royalroad.com/fiction/65789/an-immortals-retirement-to-achieve-peace/chapter/1141414/prologue
    chapter:
        section_css_selector: 'div.fic-header h1.font-white'
        title_css_selector: 'div.fic-header h1.font-white'
        text_css_selector: 'div.chapter-inner'
        next_chapter_css_selector: 'div.col-md-offset-4 a.btn'
    include_images: True
