cache: './cache/html/ADruidInGameOfThrones'
callbacks: 'books.ADruidInGameOfThrones.cbs.Callbacks'
book:
    title: A Druid İn Game Of Thrones
    author: Mikasane
    epub_filename: out/ADruidInGameOfThrones.epub
    cover_image: https://www.royalroadcdn.com/public/covers-large/a-druid-in-game-of-thrones-aacaxhfobi.jpg?time=1671648744
    css_filename: 'kindle.css'
    entry_point: https://www.royalroad.com/fiction/62184/a-druid-in-game-of-thrones/chapter/1069022/chapter-1
    chapter:
        section_css_selector: 'div.fic-header h1.font-white'
        title_css_selector: 'div.fic-header h1.font-white'
        text_css_selector: 'div.chapter-inner'
        next_chapter_css_selector: 'div.col-md-offset-4 a.btn'
    include_images: True
