cache: './cache/html/RebornAsADemonicTree'
callbacks: 'books.RebornAsADemonicTree.cbs.Callbacks'
book:
    title: Reborn as a Demonic Tree 
    author: XKARNATION 
    epub_filename: out/RebornAsADemonicTree.epub
    cover_image: https://www.royalroadcdn.com/public/covers-large/62881-reborn-as-a-demonic-tree.jpg?time=1678681868
    css_filename: 'kindle.css'
    entry_point: https://www.royalroad.com/fiction/62881/reborn-as-a-demonic-tree/chapter/1081244/chapter-1-a-scrumptious-meal
    chapter:
        section_css_selector: 'div.fic-header h1.font-white'
        title_css_selector: 'div.fic-header h1.font-white'
        text_css_selector: 'div.chapter-inner'
        next_chapter_css_selector: 'div.col-md-offset-4 a.btn'
    include_images: True
