export       TITLE="Melody of Mana"
export  FOLDERNAME="MelodyOfMana"
export      AUTHOR="Wandering Agent"
export COVER_IMAGE="https://www.royalroadcdn.com/public/covers-large/43974-melody-of-mana.jpg?time=1625071236"
export ENTRY_POINT="https://www.royalroad.com/fiction/43974/melody-of-mana/chapter/697972/chapter-1-i-am-an-idiot"
