cache: './cache/html/TheValenfrostSaga'
callbacks: 'books.TheValenfrostSaga.cbs.Callbacks'
book:
    title: "The Valenfrost Saga (A Progression Fantasy)" 
    author: Geovanny_S 
    epub_filename: out/TheValenfrostSaga.epub
    cover_image: https://www.royalroadcdn.com/public/covers-large/frost-aabafauhuri.jpg
    css_filename: 'kindle.css'
    entry_point: https://www.royalroad.com/fiction/59919/the-valenfrost-saga-a-progression-fantasy/chapter/1020768/prologue-premonition
    chapter:
        section_css_selector: 'div.fic-header h1.font-white'
        title_css_selector: 'div.fic-header h1.font-white'
        text_css_selector: 'div.chapter-inner'
        next_chapter_css_selector: 'div.col-md-offset-4 a.btn'
    include_images: True
