cache: './cache/html/ReturnOfTheRuneboundProfessor'
callbacks: 'books.ReturnOfTheRuneboundProfessor.cbs.Callbacks'
book:
    title: "Return of the Runebound Professor" 
    author: Actus 
    epub_filename: out/ReturnOfTheRuneboundProfessor.epub
    cover_image: https://www.royalroadcdn.com/public/covers-large/68679-return-of-the-runebound-professor.jpg
    css_filename: 'kindle.css'
    entry_point: https://www.royalroad.com/fiction/68679/return-of-the-runebound-professor/chapter/1218420/chapter-1-even-in-death
    chapter:
        section_css_selector: 'div.fic-header h1.font-white'
        title_css_selector: 'div.fic-header h1.font-white'
        text_css_selector: 'div.chapter-inner'
        next_chapter_css_selector: 'div.col-md-offset-4 a.btn'
    include_images: True
