cache: './cache/html/SeedsOfRuin'
callbacks: 'books.SeedsOfRuin.cbs.Callbacks'
book:
    title: "Seeds of Ruin [Farming LitRPG Comedy]" 
    author: Traxler 
    epub_filename: out/SeedsOfRuin.epub
    cover_image: https://www.royalroadcdn.com/public/covers-large/68094-seeds-of-ruin.jpg
    css_filename: 'kindle.css'
    entry_point: https://www.royalroad.com/fiction/68094/seeds-of-ruin-farming-litrpg-comedy/chapter/1204050/a-deus-ex-machina-hooray-fireworks
    chapter:
        section_css_selector: 'div.fic-header h1.font-white'
        title_css_selector: 'div.fic-header h1.font-white'
        text_css_selector: 'div.chapter-inner'
        next_chapter_css_selector: 'div.col-md-offset-4 a.btn'
    include_images: True
