cache: './cache/html/SlumratRising'
callbacks: 'books.SlumratRising.cbs.Callbacks'
book:
    title: "Slumrat Rising" 
    author: Warby Picus 
    epub_filename: out/SlumratRising.epub
    cover_image: https://www.royalroadcdn.com/public/covers-large/65801-slumrat-rising.jpg
    css_filename: 'kindle.css'
    entry_point: https://www.royalroad.com/fiction/65801/slumrat-rising/chapter/1141427/in-the-gutter
    chapter:
        section_css_selector: 'div.fic-header h1.font-white'
        title_css_selector: 'div.fic-header h1.font-white'
        text_css_selector: 'div.chapter-inner'
        next_chapter_css_selector: 'div.col-md-offset-4 a.btn'
    include_images: True
