cache: './cache/html/ParanoidMage'
callbacks: 'books.ParanoidMage.cbs.Callbacks'
book:
    title: "Paranoid Mage" 
    author: InadvisablyCompelled 
    epub_filename: out/ParanoidMage.epub
    cover_image: https://www.royalroadcdn.com/public/covers-large/49879-paranoid-mage.jpg
    css_filename: 'kindle.css'
    entry_point: https://www.royalroad.com/fiction/49879/paranoid-mage/chapter/816456/chapter-1-revelation
    chapter:
        section_css_selector: 'div.fic-header h1.font-white'
        title_css_selector: 'div.fic-header h1.font-white'
        text_css_selector: 'div.chapter-inner'
        next_chapter_css_selector: 'div.col-md-offset-4 a.btn'
    include_images: True
