cache: './cache/html/MetaworldChronicles'
callbacks: 'books.MetaworldChronicles.cbs.Callbacks'
book:
    title: Metaworld Chronicles 
    author: Wutosama 
    epub_filename: out/MetaworldChronicles.epub
    cover_image: https://www.royalroadcdn.com/public/covers-large/14167-metaworld-chronicles.jpg?time=1618748262
    css_filename: 'kindle.css'
    entry_point: https://www.royalroad.com/fiction/14167/metaworld-chronicles/chapter/163574/chapter-1-some-things-begin-something-ends
    chapter:
        section_css_selector: 'div.fic-header h1.font-white'
        title_css_selector: 'div.fic-header h1.font-white'
        text_css_selector: 'div.chapter-inner'
        next_chapter_css_selector: 'div.col-md-offset-4 a.btn'
    include_images: True
