cache: './cache/html/GarlicGravyAndGoblinGoop'
callbacks: 'books.GarlicGravyAndGoblinGoop.cbs.Callbacks'
book:
    title: "Garlic, Gravy, and Goblin Goop" 
    author: Hobogre 
    epub_filename: out/GarlicGravyAndGoblinGoop.epub
    cover_image: https://www.royalroadcdn.com/public/covers-large/61493-garlic-gravy-and-goblin-goop.jpg
    css_filename: 'kindle.css'
    entry_point: https://www.royalroad.com/fiction/61493/garlic-gravy-and-goblin-goop/chapter/1054259/chapter-1
    chapter:
        section_css_selector: 'div.fic-header h1.font-white'
        title_css_selector: 'div.fic-header h1.font-white'
        text_css_selector: 'div.chapter-inner'
        next_chapter_css_selector: 'div.col-md-offset-4 a.btn'
    include_images: True
