cache: './cache/html/AshbornPrimordial'
callbacks: 'books.AshbornPrimordial.cbs.Callbacks'
book:
    title: "Ashborn Primordial" 
    author: Vowron Prime 
    epub_filename: out/AshbornPrimordial.epub
    cover_image: https://www.royalroadcdn.com/public/covers-large/63958-ashborn-primordial.jpg
    css_filename: 'kindle.css'
    entry_point: https://www.royalroad.com/fiction/63958/ashborn-primordial/chapter/1100798/arc-1-1-the-end-of-your-world-the-beginning-of
    chapter:
        section_css_selector: 'div.fic-header h1.font-white'
        title_css_selector: 'div.fic-header h1.font-white'
        text_css_selector: 'div.chapter-inner'
        next_chapter_css_selector: 'div.col-md-offset-4 a.btn'
    include_images: True
