cache: './cache/html/TheStarsHaveEyes'
callbacks: 'books.TheStarsHaveEyes.cbs.Callbacks'
book:
    title: "The Stars Have Eyes" 
    author: Exterminatus 
    epub_filename: out/TheStarsHaveEyes.epub
    cover_image: https://www.royalroadcdn.com/public/covers-full/33261-the-stars-have-eyes.jpg
    css_filename: 'kindle.css'
    entry_point: https://www.royalroad.com/fiction/33261/the-stars-have-eyes/chapter/509280/1-arrival
    chapter:
        section_css_selector: 'div.fic-header h1.font-white'
        title_css_selector: 'div.fic-header h1.font-white'
        text_css_selector: 'div.chapter-inner'
        next_chapter_css_selector: 'div.col-md-offset-4 a.btn'
    include_images: True
