cache: './cache/html/Gleam'
callbacks: 'books.Gleam.cbs.Callbacks'
book:
    title: "Gleam" 
    author: Actus 
    epub_filename: out/Gleam.epub
    cover_image: https://www.royalroadcdn.com/public/covers-large/62157-gleam-karma-cultivator-isekai.jpg
    css_filename: 'kindle.css'
    entry_point: https://www.royalroad.com/fiction/62157/gleam/chapter/1068053/chapter-1-a-chance-encounter
    chapter:
        section_css_selector: 'div.fic-header h1.font-white'
        title_css_selector: 'div.fic-header h1.font-white'
        text_css_selector: 'div.chapter-inner'
        next_chapter_css_selector: 'div.col-md-offset-4 a.btn'
    include_images: True
