cache: './cache/html/AllTheSkills'
callbacks: 'books.AllTheSkills.cbs.Callbacks'
book:
    title: "All The Skills - A Deckbuilding LitRPG" 
    author: HonourRae 
    epub_filename: out/AllTheSkills.epub
    cover_image: https://www.royalroadcdn.com/public/covers-large/55687-all-the-skills-a-deckbuilding-litrpg.jpg
    css_filename: 'kindle.css'
    entry_point: https://www.royalroad.com/fiction/55687/all-the-skills-a-deckbuilding-litrpg/chapter/932107/book-1-chapter-1-murder-most-draconic
    chapter:
        section_css_selector: 'div.fic-header h1.font-white'
        title_css_selector: 'div.fic-header h1.font-white'
        text_css_selector: 'div.chapter-inner'
        next_chapter_css_selector: 'div.col-md-offset-4 a.btn'
    include_images: True
