cache: './cache/html/TheEssenceOfCultivation'
callbacks: 'books.TheEssenceOfCultivation.cbs.Callbacks'
book:
    title: The Essence of Cultivation 
    author: Agranulocytosis 
    epub_filename: out/TheEssenceOfCultivation.epub
    cover_image: https://www.royalroadcdn.com/public/covers-large/the-essence-of-cultivation-37146.jpg?time=1596484852
    css_filename: 'kindle.css'
    entry_point: https://www.royalroad.com/fiction/34710/the-essence-of-cultivation/chapter/534174/chapter-1-a-mild-miscalculation
    chapter:
        section_css_selector: 'div.fic-header h1.font-white'
        title_css_selector: 'div.fic-header h1.font-white'
        text_css_selector: 'div.chapter-inner'
        next_chapter_css_selector: 'div.col-md-offset-4 a.btn'
    include_images: True
