cache: './cache/html/OurLittleDarkAge'
callbacks: 'books.OurLittleDarkAge.cbs.Callbacks'
book:
    title: "Our little Dark Age - A timeloop LitRPG with Toads" 
    author: YJarex 
    epub_filename: out/OurLittleDarkAge.epub
    cover_image: https://www.royalroadcdn.com/public/covers-large/68755-our-little-dark-age-a-timeloop-litrpg-with.jpg
    css_filename: 'kindle.css'
    entry_point: https://www.royalroad.com/fiction/68755/our-little-dark-age-a-timeloop-litrpg-with-toads/chapter/1219692/1-you-have-died-again
    chapter:
        section_css_selector: 'div.fic-header h1.font-white'
        title_css_selector: 'div.fic-header h1.font-white'
        text_css_selector: 'div.chapter-inner'
        next_chapter_css_selector: 'div.col-md-offset-4 a.btn'
    include_images: True
