cache: './cache/html/TheEaglesFlight'
callbacks: 'books.TheEaglesFlight.cbs.Callbacks'
book:
    title: "The Eagle's Flight" 
    author: Quill 
    epub_filename: out/TheEaglesFlight.epub
    cover_image: https://www.royalroadcdn.com/public/covers-full/9500-the-eagles-flight.jpg
    css_filename: 'kindle.css'
    entry_point: https://www.royalroad.com/fiction/9500/the-eagles-flight/chapter/106718/1-journeys-end
    chapter:
        section_css_selector: 'div.fic-header h1.font-white'
        title_css_selector: 'div.fic-header h1.font-white'
        text_css_selector: 'div.chapter-inner'
        next_chapter_css_selector: 'div.col-md-offset-4 a.btn'
    include_images: True
