cache: './cache/html/TheGameAtCarousel'
callbacks: 'books.TheGameAtCarousel.cbs.Callbacks'
book:
    title: "The Game at Carousel: A Horror Movie LitRPG" 
    author: lost_rambler 
    epub_filename: out/TheGameAtCarousel.epub
    cover_image: https://www.royalroadcdn.com/public/covers-large/65629-the-game-at-carousel-a-horror-movie-litrpg.jpg
    css_filename: 'kindle.css'
    entry_point: https://www.royalroad.com/fiction/65629/the-game-at-carousel-a-horror-movie-litrpg/chapter/1137457/chapter-one-silas-the-showman
    chapter:
        section_css_selector: 'div.fic-header h1.font-white'
        title_css_selector: 'div.fic-header h1.font-white'
        text_css_selector: 'div.chapter-inner'
        next_chapter_css_selector: 'div.col-md-offset-4 a.btn'
    include_images: True
