cache: './cache/html/All_the_Dust_that_Falls'
callbacks: 'books.All_the_Dust_that_Falls.cbs.Callbacks'
book:
    title: All the Dust that Falls
    author: zaifyr
    epub_filename: out/All_the_Dust_that_Falls.epub
    cover_image: https://www.royalroadcdn.com/public/covers-large/60292-all-the-dust-that-falls-a-roomba-isekai.jpg?time=1668461934
    css_filename: 'kindle.css'
    entry_point: https://www.royalroad.com/fiction/60292/all-the-dust-that-falls-a-roomba-isekai-adventure/chapter/1027997/chapter-1-consequences-of-a-power-vacuum
    chapter:
        section_css_selector: 'div.fic-header h1.font-white'
        title_css_selector: 'div.fic-header h1.font-white'
        text_css_selector: 'div.chapter-inner'
        next_chapter_css_selector: 'div.col-md-offset-4 a.btn'
    include_images: True
