cache: './cache/html/SylverSeeker'
callbacks: 'books.SylverSeeker.cbs.Callbacks'
book:
    title: Sylver Seeker 
    author: Kennit Kenway 
    epub_filename: out/SylverSeeker.epub
    cover_image: https://www.royalroadcdn.com/public/covers-large/36065-sylver-seeker.jpg?time=1604603353
    css_filename: 'kindle.css'
    entry_point: https://www.royalroad.com/fiction/36065/sylver-seeker/chapter/557136/ch001-a-false-start
    chapter:
        section_css_selector: 'div.fic-header h1.font-white'
        title_css_selector: 'div.fic-header h1.font-white'
        text_css_selector: 'div.chapter-inner'
        next_chapter_css_selector: 'div.col-md-offset-4 a.btn'
    include_images: True
