cache: './cache/html/TheQuestGiver'
callbacks: 'books.TheQuestGiver.cbs.Callbacks'
book:
    title: "The Quest Giver [An NPC LitRPG Adventure]" 
    author: A. Stargazer 
    epub_filename: out/TheQuestGiver.epub
    cover_image: https://www.royalroadcdn.com/public/covers-large/64484-the-quest-giver-a-npc-litrpg-adventure.jpg
    css_filename: 'kindle.css'
    entry_point: https://www.royalroad.com/fiction/64484/the-quest-giver-an-npc-litrpg-adventure/chapter/1112113/1-quest-declined
    chapter:
        section_css_selector: 'div.fic-header h1.font-white'
        title_css_selector: 'div.fic-header h1.font-white'
        text_css_selector: 'div.chapter-inner'
        next_chapter_css_selector: 'div.col-md-offset-4 a.btn'
    include_images: True
