cache: './cache/html/TheWitchOfTophetCounty'
callbacks: 'books.TheWitchOfTophetCounty.cbs.Callbacks'
book:
    title: "The Witch of Tophet County" 
    author: jhschiller 
    epub_filename: out/TheWitchOfTophetCounty.epub
    cover_image: https://www.royalroadcdn.com/public/covers-large/the-witch-of-tophet-county-aaba3hznyrm.jpg
    css_filename: 'kindle.css'
    entry_point: https://www.royalroad.com/fiction/68787/the-witch-of-tophet-county/chapter/1220596/1-read-at-your-own-risk
    chapter:
        section_css_selector: 'div.fic-header h1.font-white'
        title_css_selector: 'div.fic-header h1.font-white'
        text_css_selector: 'div.chapter-inner'
        next_chapter_css_selector: 'div.col-md-offset-4 a.btn'
    include_images: True
