cache: './cache/html/EndsOfMagic'
callbacks: 'books.EndsOfMagic.cbs.Callbacks'
book:
    title: "Ends of Magic: Antimage LitRPG" 
    author: "Salk's Disciple" 
    epub_filename: out/EndsOfMagic.epub
    cover_image: https://www.royalroadcdn.com/public/covers-large/ends-of-magic-aabave1s-xe.jpg
    css_filename: 'kindle.css'
    entry_point: https://www.royalroad.com/fiction/57697/ends-of-magic-antimage-litrpg/chapter/972224/chapter-1-a-long-trip
    chapter:
        section_css_selector: 'div.fic-header h1.font-white'
        title_css_selector: 'div.fic-header h1.font-white'
        text_css_selector: 'div.chapter-inner'
        next_chapter_css_selector: 'div.col-md-offset-4 a.btn'
    include_images: True
