cache: './cache/html/Netherborne'
callbacks: 'books.Netherborne.cbs.Callbacks'
book:
    title: Netherborne [An OP Monster Isekai] 
    author: XKARNATION 
    epub_filename: out/Netherborne.epub
    cover_image: https://www.royalroadcdn.com/public/covers-large/64709-netherborne-book-1-complete.jpg?time=1678838149
    css_filename: 'kindle.css'
    entry_point: https://www.royalroad.com/fiction/64709/netherborne-an-op-monster-isekai/chapter/1116812/prologue
    chapter:
        section_css_selector: 'div.fic-header h1.font-white'
        title_css_selector: 'div.fic-header h1.font-white'
        text_css_selector: 'div.chapter-inner'
        next_chapter_css_selector: 'div.col-md-offset-4 a.btn'
    include_images: True
