cache: './cache/html/WolfOfTheBloodMoon'
callbacks: 'books.WolfOfTheBloodMoon.cbs.Callbacks'
book:
    title: "Wolf of the Blood Moon: A Blood Magic Lycanthrope LitRPG" 
    author: WolfShine 
    epub_filename: out/WolfOfTheBloodMoon.epub
    cover_image: https://www.royalroadcdn.com/public/covers-large/65324-wolf-of-the-blood-moon-a-blood-magic-lycanthrope.jpg
    css_filename: 'kindle.css'
    entry_point: https://www.royalroad.com/fiction/65324/wolf-of-the-blood-moon-a-blood-magic-lycanthrope/chapter/1131501/b1-chapter-1-a-visit-gone-wrong
    chapter:
        section_css_selector: 'div.fic-header h1.font-white'
        title_css_selector: 'div.fic-header h1.font-white'
        text_css_selector: 'div.chapter-inner'
        next_chapter_css_selector: 'div.col-md-offset-4 a.btn'
    include_images: True
