cache: './cache/html/TheHeartIsAVoid_AshesToAshes'
callbacks: 'books.TheHeartIsAVoid_AshesToAshes.cbs.Callbacks'
book:
    title: "The Heart is a Void: Ashes to Ashes"
    author: "MOROSE"
    epub_filename: out/TheHeartIsAVoid_AshesToAshes.epub
    cover_image: https://www.royalroadcdn.com/public/covers-full/the-heart-is-a-void-ashes-to-ashes-aaaarjtqcra.jpg
    css_filename: 'kindle.css'
    entry_point: https://www.royalroad.com/fiction/47411/the-heart-is-a-void-ashes-to-ashes/chapter/766336/prologue-for-the-glory
    chapter:
        section_css_selector: 'div.fic-header h1.font-white'
        title_css_selector: 'div.fic-header h1.font-white'
        text_css_selector: 'div.chapter-inner'
        next_chapter_css_selector: 'div.col-md-offset-4 a.btn'
    include_images: True
