cache: './cache/html/BSO'
callbacks: 'books.BSO.cbs.Callbacks'
book:
    title: Blade Skill Online
    author: Mazi Manzi
    epub_filename: out/BSO.epub
    cover_image: https://zkytl.files.wordpress.com/2022/09/51l1vq6m2vl.jpg
    css_filename: 'kindle.css'

chapter:
    section: 'Blade Skill Online'
    title_css_selector: 'h1.entry-title'
    text_css_selector: 'div.entry-content p.has-text-color'

crawl:
    entry_point: https://zkytl.wordpress.com/2022/09/14/bso-chapter-prologue/
    next_chapter_css_selector: 'div.entry-content a[title="Next"]'
crawl:
    entry_point: https://zkytl.wordpress.com/2022/09/14/bso-chapter-3/ 
    next_chapter_css_selector: 'div.entry-content a[title="Next"]'
