cache: './cache/html/anathema'
callbacks: 'books.anathema.anathema.AnathemaCallbacks'
book:
    title: Anathema
    author: chrysalis
    epub_filename: ./books/anathema/anathema.epub
    css_filename: 'kindle.css'
    table_of_contents:
        url: 'https://anathemaserial.wordpress.com/table-of-contents/'
        chapter_link_css_selector: 'div.entry-content p a:not([href*="share"])'
    chapter:
        title_css_selector: 'h1.entry-title'
        section_css_selector: 'h1.entry-title'
        text_css_selector: 'div.entry-content p'
