cache: './cache/html/TheShadowsBecomeHer'
callbacks: 'books.TheShadowsBecomeHer.cbs.Callbacks'
book:
    title: The Shadows Become Her 
    author: CLRobison 
    epub_filename: out/TheShadowsBecomeHer.epub
    cover_image: https://www.royalroadcdn.com/public/covers-large/the-shadow-becomes-her-aaaatjntthe.jpg?time=1648954447
    css_filename: 'kindle.css'
    entry_point: https://www.royalroad.com/fiction/52964/the-shadows-become-her/chapter/877012/1-a-shadows-start-i
    chapter:
        section_css_selector: 'div.fic-header h1.font-white'
        title_css_selector: 'div.fic-header h1.font-white'
        text_css_selector: 'div.chapter-inner'
        next_chapter_css_selector: 'div.col-md-offset-4 a.btn'
    include_images: True
