cache: './cache/html/Elydes'
callbacks: 'books.Elydes.cbs.Callbacks'
book:
    title: "Elydes" 
    author: Drewells 
    epub_filename: out/Elydes.epub
    cover_image: https://www.royalroadcdn.com/public/covers-large/elydes-aadaryverbm.jpg
    css_filename: 'kindle.css'
    entry_point: https://www.royalroad.com/fiction/67742/elydes/chapter/1195353/prologue
    chapter:
        section_css_selector: 'div.fic-header h1.font-white'
        title_css_selector: 'div.fic-header h1.font-white'
        text_css_selector: 'div.chapter-inner'
        next_chapter_css_selector: 'div.col-md-offset-4 a.btn'
    include_images: True
