cache: './cache/html/VainqueurTheDragon'
callbacks: 'books.VainqueurTheDragon.cbs.Callbacks'
book:
    title: Vainqueur the Dragon
    author: Maxime J. Durand 
    epub_filename: out/VainqueurTheDragon.epub
    cover_image: https://www.royalroadcdn.com/public/covers-large/26534-vainqueur-the-dragon.jpg?time=1601898849
    css_filename: 'kindle.css'
    entry_point: https://www.royalroad.com/fiction/26534/vainqueur-the-dragon/chapter/391208/1-vainqueur-the-dragon
    chapter:
        section_css_selector: 'div.fic-header h1.font-white'
        title_css_selector: 'div.fic-header h1.font-white'
        text_css_selector: 'div.chapter-inner'
        next_chapter_css_selector: 'div.col-md-offset-4 a.btn'
    include_images: True
