cache: './cache/html/ThereWillBeDragonsHere'
callbacks: 'books.ThereWillBeDragonsHere.cbs.Callbacks'
book:
    title: There Will Be Dragons Here 
    author: gliglith 
    epub_filename: out/ThereWillBeDragonsHere.epub
    cover_image: https://www.royalroadcdn.com/public/covers-large/51435-there-will-be-dragons-here.jpg?time=1665533804
    css_filename: 'kindle.css'
    entry_point: https://www.royalroad.com/fiction/51435/there-will-be-dragons-here/chapter/845777/chapter-1-beginnings
    chapter:
        section_css_selector: 'div.fic-header h1.font-white'
        title_css_selector: 'div.fic-header h1.font-white'
        text_css_selector: 'div.chapter-inner'
        next_chapter_css_selector: 'div.col-md-offset-4 a.btn'
    include_images: True
