cache: './cache/html/DungeonNoble'
callbacks: 'books.DungeonNoble.cbs.Callbacks'
book:
    title: "Dungeon Noble - Squire" 
    author: Irae153 
    epub_filename: out/DungeonNoble.epub
    cover_image: https://www.royalroadcdn.com/public/covers-large/dungeon-noble-squire-aaaa4vknixm.jpg
    css_filename: 'kindle.css'
    entry_point: https://www.royalroad.com/fiction/66448/dungeon-noble-squire/chapter/1155195/dn-1-ascension-day
    chapter:
        section_css_selector: 'div.fic-header h1.font-white'
        title_css_selector: 'div.fic-header h1.font-white'
        text_css_selector: 'div.chapter-inner'
        next_chapter_css_selector: 'div.col-md-offset-4 a.btn'
    include_images: True
