cache: './cache/html/ANovelConcept'
callbacks: 'books.ANovelConcept.cbs.Callbacks'
book:
    title: "A Novel Concept - A death a day, MC will live anyway!" 
    author: Priam 
    epub_filename: out/ANovelConcept.epub
    cover_image: https://www.royalroadcdn.com/public/covers-large/66455-a-novel-concept-a-death-a-day-mc-will-live.jpg
    css_filename: 'kindle.css'
    entry_point: https://www.royalroad.com/fiction/66455/a-novel-concept-a-death-a-day-mc-will-live-anyway/chapter/1155206/chapter-1-an-unexpected-journey
    chapter:
        section_css_selector: 'div.fic-header h1.font-white'
        title_css_selector: 'div.fic-header h1.font-white'
        text_css_selector: 'div.chapter-inner'
        next_chapter_css_selector: 'div.col-md-offset-4 a.btn'
    include_images: True
