cache: './cache/html/MotherOfLearning'
callbacks: 'books.MotherOfLearning.cbs.Callbacks'
book:
    title: Mother Of Learning
    author: nobody103
    epub_filename: out/MotherOfLearning.epub
    cover_image: https://www.royalroadcdn.com/public/covers-large/21220-mother-of-learning.jpg?time=1637247458
    css_filename: 'kindle.css'
    entry_point: https://www.royalroad.com/fiction/21220/mother-of-learning/chapter/301778/1-good-morning-brother
    chapter:
        section_css_selector: 'div.fic-header h1.font-white'
        title_css_selector: 'div.fic-header h1.font-white'
        text_css_selector: 'div.chapter-inner'
        next_chapter_css_selector: 'div.col-md-offset-4 a.btn'

# These cursom variables, may be refered to in the callback sript.
#   The 'load_images' flag, inicates whether or not images found in the content 
#   should be included in the epub.
custom:
  load_images: False
