cache: './cache/html/TheNewtAndDemon'
callbacks: 'books.TheNewtAndDemon.cbs.Callbacks'
book:
    title: "The Newt and Demon (Alchemy slice of life with townbuilding)" 
    author: emgriffiths 
    epub_filename: out/TheNewtAndDemon.epub
    cover_image: https://www.royalroadcdn.com/public/covers-large/55927-the-newt-and-demon-alchemy-slice-of-life.jpg
    css_filename: 'kindle.css'
    entry_point: https://www.royalroad.com/fiction/55927/the-newt-and-demon-alchemy-slice-of-life-with/chapter/1144229/maps-and-misc-information
    chapter:
        section_css_selector: 'div.fic-header h1.font-white'
        title_css_selector: 'div.fic-header h1.font-white'
        text_css_selector: 'div.chapter-inner'
        next_chapter_css_selector: 'div.col-md-offset-4 a.btn'
    include_images: True
